name: Caddy
package: com.github.moonfruit.caddy
version: 2.10.2
description: Fast and extensible multi-platform HTTP/1-2-3 web server with automatic HTTPS
license: https://choosealicense.com/licenses/apache-2.0/
homepage: https://github.com/caddyserver/caddy
author: MoonFruit
application:
  subdomain: caddy
  background_task: true
  multi_instance: true
  upstreams:
    - location: /
      backend: http://caddy/
      use_backend_host: false
services:
  caddy:
    image: caddy:2.10.2
    binds:
      - /lzcapp/pkg/content/caddy:/pkg
      - /lzcapp/var/config:/config
      - /lzcapp/var/data:/data
      - /lzcapp/var/caddy:/etc/caddy
      - /lzcapp/run/mnt/home/Public:/srv
    setup_script: /pkg/init.sh
