application:
  subdomain: caddy
  background_task: true
  multi_instance: true
  upstreams:
    - location: /
      backend: http://caddy/
      use_backend_host: false
services:
  caddy:
    image: caddy:2.11.3
    binds:
      - /lzcapp/pkg/content/caddy:/pkg
      - /lzcapp/var/config:/config
      - /lzcapp/var/data:/data
      - /lzcapp/var/caddy:/etc/caddy
      - /lzcapp/run/mnt/home/Public:/srv
    setup_script: /pkg/init.sh
