package: com.github.moonfruit.caddy
version: 2.11.2
name: Caddy
description: Fast and extensible multi-platform HTTP/1-2-3 web server with automatic HTTPS
author: MoonFruit
license: https://choosealicense.com/licenses/apache-2.0/
homepage: https://github.com/caddyserver/caddy
