name: AriaNg
package: com.github.moonfruit.ariang
version: 1.37.0
description: AriaNg, a modern web frontend making aria2 easier to use
license: https://choosealicense.com/licenses/gpl-3.0/
homepage: https://github.com/mayswind/AriaNg
author: MoonFruit
application:
  subdomain: aria2
  background_task: true
  multi_instance: true
  routes:
    - /=file:///lzcapp/pkg/content/ariang
  upstreams:
    - location: /rpc
      backend: http://aria2:6800/rpc
      trim_url_suffix: /
    - location: /jsonrpc
      backend: http://aria2:6800/jsonrpc
      trim_url_suffix: /
services:
  aria2:
    image: ghcr.io/moonfruit/aria2:1.37.0-r1
    binds:
      - /lzcapp/pkg/content/aria2:/pkg
      - /lzcapp/var/aria2:/root/.aria2
      - /lzcapp/run/mnt/home/Downloads:/downloads
    setup_script: /pkg/init.sh
  crond:
    image: ghcr.io/moonfruit/crond:8.14.1-r1
    binds:
      - /lzcapp/pkg/content/crond:/etc/crontabs
    depends_on:
      - aria2
    setup_script: /etc/crontabs/update-settings.sh
