application:
  subdomain: pvz2
  upstreams:
    - location: /
      backend: http://pvz2/
  public_path:
    - /
services:
  pvz2:
    image: gaozih/pvzge@sha256:5df17f8286e0591ae8bf9578ed8fa5252f35dadc457c9c51fadfeade8db5f3b1
