name: VueTorrent
package: com.github.moonfruit.vuetorrent
version: 2.7.0
description: The sleekest looking WEBUI for qBittorrent made with Vuejs!
license: https://choosealicense.com/licenses/gpl-3.0/
homepage: https://github.com/VueTorrent/vuetorrent-backend
author: MoonFruit
application:
  subdomain: vuetorrent
  background_task: true
  multi_instance: true
  routes:
    - /=http://vue/
services:
  qbit:
    image: lscr.io/linuxserver/qbittorrent:5.1.2-r3-ls419
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=80
      - TORRENTING_PORT=6881
    binds:
      - /lzcapp/pkg/content/vue:/custom-cont-init.d
      - /lzcapp/var/qbittorrent:/config
      - /lzcapp/run/mnt/home:/home
  vue:
    image: ghcr.io/vuetorrent/vuetorrent-backend:2.7.0
    environment:
      - TZ=Asia/Shanghai
      - PORT=80
      - QBIT_BASE=http://qbit
      - RELEASE_TYPE=stable
      - UPDATE_VT_CRON=0 * * * *
      {{- if .U.GithubToken }}
      - GITHUB_AUTH={{ .U.GithubAuth }}
      {{- end }}
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/vuetorrent:/vuetorrent
