application:
  subdomain: vuetorrent
  background_task: true
  multi_instance: true
  routes:
    - /=http://vue/
services:
  qbit:
    image: lscr.io/linuxserver/qbittorrent:5.2.0_v2.0.12-ls458
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=6880
      - TORRENTING_PORT=6881
    network_mode: host
    binds:
      - /lzcapp/pkg/content/vue:/custom-cont-init.d
      - /lzcapp/var/qbittorrent:/config
      - /lzcapp/run/mnt/home:/home
  vue:
    image: ghcr.io/vuetorrent/vuetorrent-backend:2.7.3
    depends_on:
      - qbit
    environment:
      - TZ=Asia/Shanghai
      - PORT=80
      - QBIT_BASE=http://_outbound:6880
      - RELEASE_TYPE=stable
      - UPDATE_VT_CRON=0 * * * *
      {{- if .U.GithubToken }}
      - GITHUB_AUTH={{ .U.GithubAuth }}
      {{- end }}
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/vuetorrent:/vuetorrent
