package: com.github.moonfruit.vuetorrent
version: 2.7.2
name: VueTorrent
description: The sleekest looking WEBUI for qBittorrent made with Vuejs!
author: MoonFruit
license: https://choosealicense.com/licenses/gpl-3.0/
homepage: https://github.com/VueTorrent/vuetorrent-backend
