application:
  subdomain: myip
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://myip:18966/
      use_backend_host: false
services:
  myip:
    image: jason5ng32/myip:v6.5.0
    environment:
      - ALLOWED_DOMAINS=myip.${LAZYCAT_BOX_DOMAIN}
