name: Build image for crond

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-crond.yml"
      - "docker/crond/Dockerfile"
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: extract
        run: |
          VERSION=$(grep -oP '(?<=CURL_VERSION=)\S*' docker/crond/Dockerfile)
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha,scope=crond
          cache-to: type=gha,scope=crond,mode=max
          context: docker/crond
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/crond:${{ steps.extract.outputs.version }}
            ghcr.io/${{ github.actor }}/crond:latest

      - name: Generate attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.actor }}/crond
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
